// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChOdy9Rq1QINy7vidCwvinfvNxxKAtmMk',
    appId: '1:296311545823:web:9930a576cf552b6984ee6a',
    messagingSenderId: '296311545823',
    projectId: 'ecommerce-e18ea',
    authDomain: 'ecommerce-e18ea.firebaseapp.com',
    storageBucket: 'ecommerce-e18ea.appspot.com',
    measurementId: 'G-JN4JWML66R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvJ9cSAt3XOHUcv64HxDGyvWse3VX7UeY',
    appId: '1:296311545823:android:8756ae2f891d03f284ee6a',
    messagingSenderId: '296311545823',
    projectId: 'ecommerce-e18ea',
    storageBucket: 'ecommerce-e18ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRN9lrpI2R5hl3gGoYMosYubCBdejmf5k',
    appId: '1:296311545823:ios:48b2946030c6006784ee6a',
    messagingSenderId: '296311545823',
    projectId: 'ecommerce-e18ea',
    storageBucket: 'ecommerce-e18ea.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRN9lrpI2R5hl3gGoYMosYubCBdejmf5k',
    appId: '1:296311545823:ios:48b2946030c6006784ee6a',
    messagingSenderId: '296311545823',
    projectId: 'ecommerce-e18ea',
    storageBucket: 'ecommerce-e18ea.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChOdy9Rq1QINy7vidCwvinfvNxxKAtmMk',
    appId: '1:296311545823:web:5395e53cd31d8eaa84ee6a',
    messagingSenderId: '296311545823',
    projectId: 'ecommerce-e18ea',
    authDomain: 'ecommerce-e18ea.firebaseapp.com',
    storageBucket: 'ecommerce-e18ea.appspot.com',
    measurementId: 'G-L1G33BL218',
  );
}
